---
- hosts: all
  become: true
  tasks:
    - name: change hostname
      hostname:
        name: miqdev
    - name: install OS elements
      dnf: name=* state=latest
    - name: install OS packages for development
      dnf: name={{ item }} state=latest
      with_items:
        - dnf-plugins-core
        - git-all
        - memcached
        - postgresql-devel
        - postgresql-server
        - bzip2 
        - libffi-devel
        - readline-devel
        - libxml2
        - libxml2-devel
        - libxslt-devel
        - patch
        - sqlite-devel
        - nodejs
        - gcc-c++
        - libcurl-devel
        - npm
        - openssl-devel
        - cmake
        - python3-psycopg2
        - python3-libselinux
        - bash-completion
        - vim
    - name: install npm packages needed
      npm: name={{ item }} global=yes
      with_items:
        - bower
        - yarn
        - webpack
    - name: enable memcached and ensure is running
      service: name=memcached state=started enabled=yes
    - name: Initiate database
      command: service postgresql initdb
               creates=/var/lib/pgsql/data/postgresql.conf
    - name: configure pg_hba.conf
      replace: dest=/var/lib/pgsql/data/pg_hba.conf 
                  regexp='^(local\s*\w*\s*\w*\s*)(peer)'
                  replace='\1trust' 
                  backup=yes
    - name: Start PostgreSQL and enable at boot
      service: name=postgresql
               enabled=yes
               state=started
    - name: create user in postgres
      postgresql_user: name=root password=smartvm state=present role_attr_flags=SUPERUSER
- hosts: all
  vars:
    ruby_version: "2.6.6"
  become: false
  tasks:
    - name: git clone rbenv
      git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv
    - name: git clone  ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    - name: set up PATH for rbenv
      lineinfile: dest=~/.bashrc line='export PATH="$HOME/.rbenv/bin:$PATH"'
    - name: autoload rbenv init
      lineinfile: dest=~/.bashrc line='eval "$(rbenv init -)"'
    - name: ruby version to be used
      lineinfile: dest=~/.bashrc line='export RBENV_VERSION="{{ ruby_version }}"'
    - name: install ruby version {{ ruby_version }}
      shell: rbenv install -s {{ ruby_version }}
- hosts: all
  become: true
  tasks:
    - name: verify if we need to reboot
      command: dnf needs-restarting
      register: reboot_needed
    - name: reboot machine
      shell: shutdown -t 5 -r now "Rebooting as the appliance needs restarting"
      async: 0
      poll: 0
      ignore_errors: yes
      when: reboot_needed.stdout != ""
    - name: waiting for server to come back
      wait_for_connection:
        delay: 60
        timeout: 300
...
